add_subdirectory(lockfree)
add_subdirectory(logging)
add_subdirectory(perfmeasure)
add_subdirectory(memory)
add_subdirectory(time)
add_subdirectory(serialization)
add_subdirectory(config)
add_subdirectory(hashmap)
add_subdirectory(networking)
add_subdirectory(testing)
add_subdirectory(cmdline)
add_subdirectory(app)
add_subdirectory(threadpool)
add_subdirectory(orderbook)
